name: Build Test
on:
  push:
    branches:
      - main
jobs:
  Build:
    name: Build Linux Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Building
        run: |
          go build main.go
      
          mkdir release
          cp main release/main
      - name: Uploading
        uses: actions/upload-artifact@v1
        with:
          name: release_linux # 
          path: release # 
